server:
  port: 7001

spring:
  application:
    name: cloud-eureka-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-erueka: false
    fetch-register: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/